### ISSUE TITLE
fbind doesn't work properly when the directory name contains spaces

### ISSUE THREAD

**Issue by nggit** [VR-25/fbind#1]
It will prevent the applications from creating new files (write-protected), but OK for new folders.

This only happens when using **sdcardfs** mode. In **FUSE** mode, there is no problem, but **FUSE** mode tends to be slow for me. 

Config I use:

`from_to "WhatsApp Business" ".fbind/WhatsApp Business"`

![Screenshot_20200123-133729](https://user-images.githubusercontent.com/12218311/72962473-ff1bb600-3de6-11ea-9d49-4b5d3e00da65.png)

Thank you!

**Comment by ammar0466** [comment]
This is my workflow
Type in config : 
`int_extf .fbind`

Manual move all folder from internal to sdcard, in .fbind folder.

Then open terminal type in : 
fbind -Mm

**Comment by nggit** [comment]
Thanks. It works well. But because my .fbind directory isn't empty, `fbind -Mm` actually destroys my folders and files that are already in .fbind. (T.T). May be `fbind -Mm` is only needed when .fbind does not contain anything?

**Comment by ammar0466** [comment]
So just used `fbind -m`

**Comment by VR-25** [comment]
@nggit, do you still face this issue with the latest version?

P.S., `fbind -Mm` (move and mount) wipes the destination before moving data into it!

**Comment by nggit** [comment]
I ended up not mounting per directory, but the whole sdcard using `int_extf .fbind` as suggested by @ammar0466. Working fine until now. Maybe this case should now be closed? Thank you @VR-25
