### ISSUE TITLE
Question: is there a way to mount a folder from intsd to intsd?

### ISSUE THREAD

**Issue by soredake** [VR-25/fbind#13]
i tried `bind_mount $intsd/Download/DTF $intsd/merged` but it doesn't work.

**Comment by VR-25** [comment]
Hm, it should have worked.
Try the attached pre-release.
[fbind_magisk_2022-02-11_19.13.23.zip](https://github.com/VR-25/fbind/files/8050958/fbind_magisk_2022-02-11_19.13.23.zip)

**Comment by soredake** [comment]
Unfortunately, it's still doesn't working.

**Comment by VR-25** [comment]
Try different paths under /mnt.
e.g., `bind_mount /mnt/pass_through/0/emulated/0/Download/DTF /mnt/pass_through/0/emulated/0/merged`
This would have been very straightforward, if only Android had well-defined standards and less fragmentation.

**Comment by soredake** [comment]
Thanks, it works with this path! Can you please mention this use-case is readme?

**Comment by VR-25** [comment]
Sure.
The next update is bringing several changes regarding paths.

**Comment by soredake** [comment]
Thank you again.
