### ISSUE TITLE
Request?

### ISSUE THREAD

**Issue by ELKecham** [VR-25/fbind#15]
Bind /storage/2116-31F4/ -> /mnt/sdcard/something

storage/2116-31F4/ -> /storage/0/something

This is possible ? Just like folder mount or similar ?

I need to bind/mount a root/ folder to -> storage

**Comment by VR-25** [comment]
Add `bind_mount target mount_point` to your config. Use $intsd and $extsd for internal and external storage, respectively. There are examples in the readme.
