### ISSUE TITLE
Support for Android 10

### ISSUE THREAD

**Issue by Exeedy** [VR-25/fbind#2]
Thank you @VR-25  for these awesome scripts/plugins you made. The plugin "fbind" is one of my most needed tweaks but it doesn't work on Android 10/SDK 29 - SM-G975F 😔
Would be really happy if you could update "fbind". All your tweaks are very needed 😉

Big thank you
Greetings

(Sorry for misuse of the bug section)

**Comment by ammar0466** [comment]
You could try the fix by other xda member on xda page, 
https://forum.xda-developers.com/apps/magisk/module-magic-folder-binder-t3621814/page167/amp/

https://forum.xda-developers.com/attachment.php?attachmentid=4926165
