### ISSUE TITLE
Install Failed Magisk 20.4

### ISSUE THREAD

**Issue by yogifrog** [VR-25/fbind#3]
When i Try to Install Fbind module then Installation Failed, Magisk v20.4

**Comment by pablojrl123** [comment]
Same here. (As a side note I have had some difficulties with other modules in v20.4 as well)

**Comment by lzkk4** [comment]
v20.4 can install but not showed in  manager, back to v20.2 can work

**Comment by a0193143** [comment]
There's a new version (v2020.8.4) in Telegram channel, can be installed on v20.4 Magisk Manager
