### ISSUE TITLE
fbind media option from menu deleted all files in destination folder

### ISSUE THREAD

**Issue by ANTONIOPSD** [VR-25/fbind#5]
Well I manually created the .fbin/WhatApp/Media folders and moved all files before running fbind, then I launched fbind menu and used the "media" option and I typed WhatsApp/Media then it asked this: Move data & bind folders now (y/N)?
and I selected "y" but that deleted all existing files in the destination folder instead of merging them.

**Comment by VR-25** [comment]
_Move data & bind folders now (y/N)?_ assumes the destination is new and clean.
As of now, I'm not sure about the idea of merging.
As I think about it, fbind will rename existing folders to <foldername>.old.
