### ISSUE TITLE
All files in internal storage goes invisible after mounting 

### ISSUE THREAD

**Issue by ali-oem** [VR-25/fbind#6]
After mounting any file in android 11, all files in internal storage are invisible (Not deleted).
![Screenshot_20210510-154718_Files.png](https://user-images.githubusercontent.com/71282548/117761986-34d4f000-b220-11eb-94bc-e4cc0a76e9fd.png).
The terminal showed no particular error message.

**Comment by VR-25** [comment]
Should work now.
