### ISSUE TITLE
Script doesn't work, nothing happens, terminal just hangs.

### ISSUE THREAD

**Issue by ioogithub** [VR-25/fbind#7]
The script was successfully installed with Magisk 22.1.

At the terminal when fbind is run:

fbind

fbind -h

nothing happens, no output the terminal just hangs.

No other terminal commands work and the service with a simple config doesn't work either. I see a new version was recently released so I don't think this is a dead project but many of the telegram links are broken.

LineageOS 17.1
Magisk 20.4
fbind v2021.3.4
river

**Comment by VR-25** [comment]
Try the latest prerelease.

**Comment by Ajaymamtora** [comment]
Same issue here, with the latest version of fbind and canary magic (23014), Derp ROM Android 11,Mi 11, except the device doesn't hang it just immediately just outputs nothing to the terminal

**Comment by VR-25** [comment]
See if [this](https://forum.xda-developers.com/t/fbind.3621814/post-85941825) helps.

**Comment by Ajaymamtora** [comment]
@VR-25 I tried those steps and the script still outputs nothing:
![2021-11-14 16 19 37](https://user-images.githubusercontent.com/45173937/141689234-ecf5624c-0e2f-44b9-ad4e-c0af26440534.jpg)

**Comment by VR-25** [comment]
> Also forgot to mention, not using an SD Card. I was experimenting with trying to get my rclone mount mounted in my internal SD
The program expects a mounted sdcard or instructions to mount/locate one.
Adding the following line to your config will work:
`extsd_path $intsd`

Upgrade first.
[fbind-2021.11.14.18.26.57.zip](https://github.com/VR-25/fbind/files/7534258/fbind-2021.11.14.18.26.57.zip)

**Comment by VR-25** [comment]
One more
[fbind-2021.11.14.18.36.12.zip](https://github.com/VR-25/fbind/files/7534282/fbind-2021.11.14.18.36.12.zip)

**Comment by Ajaymamtora** [comment]
> One more
> [fbind-2021.11.14.18.36.12.zip](https://github.com/VR-25/fbind/files/7534282/fbind-2021.11.14.18.36.12.zip)

Okay just tried the last one and it just hangs when I invoke fbind, I've added that line you suggested too, terminal.log contents:

```
Sun Nov 14 17:43:32 GMT 2021
versionCode=202111141
744: '[' -f /data/adb/modules/vr25.fbind/system.prop ']'
754: 2>/dev/null 
754: rm /data/adb/vr25/fbind-data/.FUSE
757: false
757: apply_config
9: '[' -f /data/adb/vr25/fbind-data/config.txt ']'
10: grep -iq ^permissive /data/adb/vr25/fbind-data/config.txt
14: is_mounted /mnt/runtime/write/emulated
210: 2>/dev/null 
210: mountpoint -q /mnt/runtime/write/emulated
14: is_mounted /mnt/runtime/write/emulated/0
210: 2>/dev/null 
210: mountpoint -q /mnt/runtime/write/emulated/0
15: intsd=/data/media/0 
16: obb=/data/media/0/Android/obb 
20: grep -q '^extsd_path ' /data/adb/vr25/fbind-data/config.txt
24: is_mounted
210: 2>/dev/null 
210: mountpoint -q ''
25: extsd0='' 
26: extobb0='' 
27: extsd=/mnt/media_rw/ 
28: extobb=/mnt/media_rw//Android/obb 
31: >/dev/.vr25/fbind/tmpf 
31: grep -E '^extsd_path |^intsd_path |^part |^loop ' /data/adb/vr25/fbind-data/config.txt
32: . /dev/.vr25/fbind/tmpf
1: intsd_path /mnt/runtime/write/emulated/0
205: intsd=/mnt/runtime/write/emulated/0 
206: obb=/mnt/runtime/write/emulated/0/Android/obb 
2: extsd_path /mnt/runtime/write/emulated/0
164: altExtsd=true 
165: '[' /mnt/runtime/write/emulated/0 '=' /mnt/runtime/write/emulated/0 ']'
166: extsd=/mnt/runtime/write/emulated/0 
167: extobb=/mnt/runtime/write/emulated/0/Android/obb 
172: wait_until_true is_mounted /mnt/runtime/write/emulated/0
633: set +x
172: exxit
177: typeset 'exitCode=130'
178: echo
179: 2>/dev/null 
179: rm /data/adb/vr25/fbind-data/.FUSE.tmp
180: exit 130
```

**Comment by VR-25** [comment]
Your device seems to have some unusual mount scheme.
Share the output of `mount`.

**Comment by Ajaymamtora** [comment]
[Uploading mount.txt…]()

**Comment by VR-25** [comment]
> [mount.txt](https://github.com/VR-25/fbind/files/7534828/mount.txt)
> 

Is this from Android 11+ with kernel 5.4+?

See if having the following lines in your config helps (upgrade first; new build coming soon):
```
intsd_path /mnt/pass_through/0/emulated/0
extsd_path $intsd
```

P.S., I would like to see another mount.txt with the sdcard mounted to complete this puzzle.

**Comment by VR-25** [comment]
[fbind-2021.11.15.07.09.26.zip](https://github.com/VR-25/fbind/files/7536269/fbind-2021.11.15.07.09.26.zip)
This does not require the aforementioned config lines.

**Comment by Ajaymamtora** [comment]
> [fbind-2021.11.15.07.09.26.zip](https://github.com/VR-25/fbind/files/7536269/fbind-2021.11.15.07.09.26.zip)
> This does not require the aforementioned config lines.

Ive tried this one and fbind still hangs, I also tried the command above and still can't get it to work

**Comment by VR-25** [comment]
A new release will be up soon.
See how it behaves.

**Comment by Ajaymamtora** [comment]
> A new release will be up soon.
> See how it behaves.

Thank you, fbind works now! But my mount isn't appearing in my internal storage, am I doing something wrong? My config is as follows:

```
intsd_path /mnt/pass_through/0/emulated/0
extsd_path $intsd
bind_mount /mnt/cloud/bigpi /mnt/pass_through/0/emulated/0/bigpi
```

**Comment by VR-25** [comment]
Share `/proc/mounts` and the logs under `/data/adb/vr25/fbind-data/logs/`.
Meanwhile, see if the following config works (but unmount first: `fbind -u`):
```
intsd_path /storage/emulated/0
extsd_path $intsd
bind_mount /mnt/cloud/bigpi $intsd/big
```

**Comment by VR-25** [comment]
Nice! That's the spec sheet I was looking for.
See if the issue persists after rebooting.

**Comment by Ajaymamtora** [comment]
> [fbind-2021.11.17.16.10.39.zip](https://github.com/VR-25/fbind/files/7555940/fbind-2021.11.17.16.10.39.zip)
> This one was confirmed to work on Android 11, even with kernel 5.4.
> Try it.
> 
> Your config should only contain what you want to mount.
> `bind_mount /mnt/cloud/bigpi $intsd/big`
> 

Thanks very much! It worked with the previous fbind with that single line config you just posted, also still works with that latest build ..17.16.10. 😄
